### ISSUE TITLE
How to export data with unicode?

### ISSUE THREAD

**Issue by dinhienhy** [joshuapaling/CakePHP-Export-CSV-Plugin#3]
Hello,

My database is unicode format. So, when it export to csv file, it have a couple about font format.

Could you help me resolve that problem?
Thanks,

**Comment by joshuapaling** [comment]
Hi,

The plugin should work with a unicode-encoded database, no problems. My databases are unicode, and it's working fine for me. I'm not sure what you mean when you say "it have a couple about font format". Could you please explain your problem in more detail?

**Comment by dinhienhy** [comment]
Thanks your support,
My database has Collation "utf8_unicode_ci  ",
![result](https://f.cloud.github.com/assets/170442/1462315/3cde0740-44f1-11e3-8314-585facce8c44.PNG)

**Comment by joshuapaling** [comment]
Could you paste as text the output you are expecting to get in those two circles? As in, paste in what's stored in the database itself?

**Comment by dinhienhy** [comment]
Values is marked in 2 circles:
1. Hiá»n Phan
2. VÃ© Háº¡ng A

Values is stored in database:
1. Hiền Phan
2. Vé Hạng A

**Comment by joshuapaling** [comment]
Hi,

The plugin is exporting things correctly. Using your example, I tried exporting Hiền Phan, and then opening the resulting CSV.

It works, and shows correctly, in Sublime Text, in Text Edit, and in Numbers (Apple's equivalent to Excel). It's only when I open it in excel that it doesn't show correctly.

The problem is specific to excel. Excel doesn't handle these characters correctly. To work around it, use a different program - apparently Google Docs spreadsheets works fine.

Here's some relevant links:

http://stackoverflow.com/questions/4221176/excel-to-csv-with-utf8-encoding
http://www.accompa.com/kb/answer.html?answer_id=264
